#!/bin/sh
#
# fix conntrack-hash-size on reboot
#

BOOTFILE=$1
cthash_cfg=$(cli-shell-api cfReturnValue $BOOTFILE firewall conntrack-hash-size)

if [ -z "$cthash_cfg" ]; then
	cthash_cfg=4096 # default hashsize value that Vyatta ships
fi

if ! grep -q "nf_conntrack hashsize=$cthash_cfg$" \
	/etc/modprobe.d/vyatta_nf_conntrack.conf
then
	sudo sh -c "sed -i -e '/options nf_conntrack hashsize/d' \
		/etc/modprobe.d/vyatta_nf_conntrack.conf"
	sudo sh -c "echo options nf_conntrack hashsize=$cthash_cfg >> \
		/etc/modprobe.d/vyatta_nf_conntrack.conf"
fi
